version: '3.8'

services:
  vuestic-app:
    build:
      context: ../vuesticApiFast/my-vuestic-app
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    networks:
      - app-network

  api-fast:
    build:
      context: ../nova_cel-adal/Infinity
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
